name: Bürgermeisterwahl Scraper

on:
  schedule:
    - cron: "* * * * *"  # Läuft jede Minute
  workflow_dispatch:  # Erlaubt manuelles Starten

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Abhängigkeiten installieren
        run: pip install requests pandas beautifulsoup4

      - name: Scraper ausführen
        run: cd projekte/dashboard_buergermeisterwahl/skripte && python -m scraper

      - name: Änderungen überprüfen
        run: git status

      - name: Änderungen committen & pushen
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add daten/wahlergebnisse.csv
          git commit -m "Automatisches Update der Wahlergebnisse" || echo "Keine Änderungen zum Committen"
          git push